### ISSUE TITLE
RPY files in Game Directories are bad procedure

### ISSUE THREAD

**Issue by Vinni2K00** [Iniquitatis/DDLCComfyUI#27]
(adressing the MAS package)

Monika will ask you to please get rid of those files. Auto updating MAS won't work either.
please create subdirectories like for ex. \\game\ _Submods\ComfyUI_ for **comfy_ui.rpy** so that won't be an issue anymore.

Kindly Vinni

**Comment by Iniquitatis** [comment]
Closing as it was discussed on Reddit already.

_It's been more than a year since I touched the codebase for the last time, so I don't quite remember the reason. Maybe it has something to do with script precedence or whatever.
This mod is hacky enough (just by nature; Ren'Py limitations) already to put it on more risk._
